-- luacheck configuration for confusio
std = "lua54"
max_line_length = 200

globals = {
  -- Redbean built-ins: request inspection
  "GetMethod",
  "GetPath",
  "GetHeader",
  "GetParam",
  "GetBody",
  -- Redbean built-ins: response building
  "SetStatus",
  "SetHeader",
  "Write",
  -- Redbean built-ins: networking and encoding
  "Fetch",
  "EncodeJson",
  "DecodeJson",
  "EncodeBase64",
  "DecodeBase64",
  "EscapeParam",
  "GetCryptoHash",
  "GetRandom",
  -- Redbean built-ins: routing
  "Route",
  "OnHttpRequest",
  -- App globals defined in .init.lua, read by backends/*.lua
  "provider_families",
  "config",
  "set_preamble",
  "respond_json",
  "proxy_json",
  "proxy_json_paged",
  "proxy_json_created",
  "proxy_health_check",
  "proxy_204",
  "proxy_json_list",
  "translate_list",
  "proxy_search_envelope",
  "rewrite_link_header",
  "append_page_params",
  "make_fetch_opts",
  "make_proxy_handler",
  "make_backend_transport",
  "owner_repo_id",
  "translate_repo",
  "translate_user",
  "translate_migration",
  -- App context: constructed in .init.lua, holds config + backend state
  "app",
  "make_app",
  -- Backend builder: internal/registry.lua; backends use this instead of mutating globals
  "make_backend_builder",
  -- Capability module helpers: internal/capabilities.lua
  "cap_err",
  "cap_fetch",
  "cap_fetch_paged",
  "cap_rest_respond",
  "cap_rest_created",
  "cap_rest_204",
  "cap_rest_paged",
  -- Default stub handlers: populated by internal/defaults.lua, read by the catalog in .init.lua
  "defaults",
  -- Router: populated by internal/router.lua, used by the catalog and OnHttpRequest in .init.lua
  "route_add",
  "route_match",
  "path_known",
  -- Endpoint catalog: populated by .init.lua, read by scripts/dump-endpoints.lua
  "endpoints",
  -- GraphQL schema data: auto-generated by scripts/gen-graphql-schema.py
  "graphql_schema_data",
  -- GraphQL lexer and parser: internal/graphql_parser.lua
  "graphql_parse",
  "graphql_tokenize",
  -- GraphQL schema loader: internal/graphql_schema.lua
  "graphql_schema_type",
  "graphql_schema_field",
  "graphql_schema_base_type",
  "graphql_schema_is_nonnull",
  "graphql_schema_is_leaf",
  "graphql_schema_expand_type",
  "graphql_introspect_schema",
  "graphql_introspect_type",
  -- GraphQL executor: internal/graphql_executor.lua
  "graphql_resolvers",
  "respond_graphql",
  "graphql_error",
  "graphql_handler",
  "graphql_register_builtin_resolvers",
  "make_dispatcher",
  "make_webhook_receiver",
  -- Webhook event mapping: internal/webhook_event.lua
  "make_internal_event",
  -- UUID and timestamp utilities: internal/util.lua
  "make_uuid",
  "iso8601",
  "now_iso8601",
  -- Outbox: internal/outbox.lua
  "outbox_store_event",
  "outbox_get_event",
  "outbox_create_delivery",
  "outbox_get_delivery",
  "outbox_list_deliveries_for_event",
  "outbox_list_deliveries_for_target",
  "outbox_update_delivery",
  "outbox_pending_retries",
  "outbox_prune",
  -- Target registry: internal/targets.lua
  "target_create",
  "target_get",
  "target_list",
  "target_update",
  "target_delete",
  "target_get_secret",
  -- Target admin API: internal/targets_api.lua
  "make_targets_api",
  -- Outbound delivery signing: internal/signing.lua
  "sign_github",
  "sign_confusio",
  "get_client_mutation_id",
  "estimate_query_cost",
  -- GraphQL translators: internal/graphql_translators.lua
  "encode_node_id",
  "decode_node_id",
  "graphql_fetch",
  "graphql_fetch_with_headers",
  "graphql_fetch_or_error",
  "graphql_page_to_cursor",
  "graphql_cursor_to_page",
  "graphql_cursor_url",
  "graphql_prefetch_total_from_headers",
  "graphql_inline_connection",
  "graphql_make_connection",
  "graphql_issues_connection",
  "graphql_prs_connection",
  "graphql_repos_connection",
  "graphql_users_connection",
  "graphql_labels_connection",
  "graphql_refs_connection",
  "graphql_translate_repo",
  "graphql_translate_user",
  "graphql_translate_org",
  "graphql_translate_owner",
  "graphql_translate_issue",
  "graphql_translate_pr",
  "graphql_translate_label",
  "graphql_translate_milestone",
  "graphql_translate_comment",
  "graphql_translate_commit",
  "graphql_translate_team",
  "graphql_translate_ref",
  "graphql_translate_release",
  "graphql_translate_review",
  "graphql_translate_reaction",
}

-- Exclude auto-generated files from linting
exclude_files = {
  "internal/graphql_schema_data.lua",
  ".claude/",
}
